# Generated by Django 3.0.6 on 2020-05-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.IntegerField()),
                ('sepal_width', models.IntegerField()),
                ('petal_length', models.IntegerField()),
                ('petal_width', models.IntegerField()),
            ],
        ),
    ]
