# Generated by Django 3.0.6 on 2020-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irismodel',
            name='petal_length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='petal_width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='sepal_length',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='sepal_width',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
